# Generated by Django 5.1.1 on 2024-09-24 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('consulta_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=100, unique=True)),
                ('campos', models.TextField()),
                ('operadores1', models.CharField(default='', max_length=100)),
                ('cadenas', models.CharField(default='', max_length=200)),
                ('operadores2', models.CharField(default='', max_length=50)),
                ('consulta_sql', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Traductor',
            fields=[
                ('traductor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('cp', models.IntegerField()),
                ('pais', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=25)),
                ('f_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=9)),
                ('tlf_mv', models.CharField(blank=True, max_length=18, null=True)),
                ('tlf_fijo', models.CharField(blank=True, max_length=18, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('f_alta', models.DateTimeField()),
                ('f_acceso', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguas_nativas', models.CharField(blank=True, max_length=20, null=True)),
                ('estudios', models.CharField(blank=True, max_length=40, null=True)),
                ('titulacion', models.CharField(blank=True, max_length=50, null=True)),
                ('situacion', models.CharField(blank=True, max_length=20, null=True)),
                ('experiencia', models.IntegerField(blank=True, null=True)),
                ('textos', models.CharField(blank=True, max_length=100, null=True)),
                ('softwares', models.CharField(blank=True, max_length=250, null=True)),
                ('traductor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profesional', to='traductores.traductor')),
            ],
        ),
        migrations.CreateModel(
            name='Combinacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=20)),
                ('destino', models.CharField(max_length=20)),
                ('servicios', models.CharField(max_length=255)),
                ('tarifa_palabra', models.FloatField(blank=True, null=True)),
                ('tarifa_jurada', models.FloatField(blank=True, null=True)),
                ('tarifa_hora', models.FloatField(blank=True, null=True)),
                ('traductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinaciones', to='traductores.traductor')),
            ],
        ),
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('traductor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceso', to='traductores.traductor')),
            ],
        ),
    ]
