# Generated by Django 5.1.1 on 2024-09-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traductores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinacion',
            name='tarifa_hora',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='combinacion',
            name='tarifa_jurada',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='combinacion',
            name='tarifa_palabra',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='traductor',
            name='nombre',
            field=models.CharField(help_text='Introduzca su nombre', max_length=100),
        ),
    ]
