# Generated by Django 5.1.1 on 2024-09-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traductores', '0002_alter_combinacion_tarifa_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traductor',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=9),
        ),
    ]
