# Generated by Django 5.1.1 on 2024-09-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traductores', '0003_alter_traductor_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traductor',
            name='f_alta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
