# Generated by Django 5.1.1 on 2024-09-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traductores', '0006_alter_combinacion_destino_alter_combinacion_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilprofesional',
            name='experiencia',
            field=models.CharField(blank=True, choices=[('Sin experiencia', 'Sin experiencia'), ('Menos de 6 meses', 'Menos de 6 meses'), ('6 meses - 1 año', '6 meses - 1 año'), ('1 - 2 años', '1 - 2 años'), ('2 - 5 años', '2 - 5 años'), ('5 - 10 años', '5 - 10 años'), ('Más de 10 años', 'Más de 10 años')], max_length=20, null=True),
        ),
    ]
