# Generated by Django 5.1.1 on 2024-09-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traductores', '0007_alter_perfilprofesional_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinacion',
            name='destino',
            field=models.CharField(blank=True, choices=[('Alemán', 'Alemán'), ('Bosnio', 'Bosnio'), ('Búlgaro', 'Búlgaro'), ('Catalán', 'Catalán'), ('Checo', 'Checo'), ('Chino', 'Chino'), ('Coreano', 'Coreano'), ('Croata', 'Croata'), ('Danés', 'Danés'), ('Eslovaco', 'Eslovaco'), ('Esloveno', 'Esloveno'), ('Español', 'Español'), ('Español (MX)', 'Español (MX)'), ('Euskera', 'Euskera'), ('Filipino', 'Filipino'), ('Finés', 'Finés'), ('Francés', 'Francés'), ('Francés (CA)', 'Francés (CA)'), ('Gallego', 'Gallego'), ('Georgiano', 'Georgiano'), ('Griego', 'Griego'), ('Hebreo', 'Hebreo'), ('Hindi', 'Hindi'), ('Holandés', 'Holandés'), ('Húngaro', 'Húngaro'), ('Inglés', 'Inglés'), ('Islandés', 'Islandés'), ('Italiano', 'Italiano'), ('Japonés', 'Japonés'), ('Lituano', 'Lituano'), ('Noruego', 'Noruego'), ('Polaco', 'Polaco'), ('Portugués (BR)', 'Portugués (BR)'), ('Portugués (PT)', 'Portugués (PT)'), ('Rumano', 'Rumano'), ('Ruso', 'Ruso'), ('Serbio', 'Serbio'), ('Singalés', 'Singalés'), ('Sueco', 'Sueco'), ('Tailandés', 'Tailandés'), ('Turco', 'Turco'), ('Ucraniano', 'Ucraniano'), ('Urdu', 'Urdu'), ('Valenciano', 'Valenciano'), ('Vietnamita', 'Vietnamita'), ('Árabe', 'Árabe')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='combinacion',
            name='origen',
            field=models.CharField(blank=True, choices=[('Alemán', 'Alemán'), ('Bosnio', 'Bosnio'), ('Búlgaro', 'Búlgaro'), ('Catalán', 'Catalán'), ('Checo', 'Checo'), ('Chino', 'Chino'), ('Coreano', 'Coreano'), ('Croata', 'Croata'), ('Danés', 'Danés'), ('Eslovaco', 'Eslovaco'), ('Esloveno', 'Esloveno'), ('Español', 'Español'), ('Español (MX)', 'Español (MX)'), ('Euskera', 'Euskera'), ('Filipino', 'Filipino'), ('Finés', 'Finés'), ('Francés', 'Francés'), ('Francés (CA)', 'Francés (CA)'), ('Gallego', 'Gallego'), ('Georgiano', 'Georgiano'), ('Griego', 'Griego'), ('Hebreo', 'Hebreo'), ('Hindi', 'Hindi'), ('Holandés', 'Holandés'), ('Húngaro', 'Húngaro'), ('Inglés', 'Inglés'), ('Islandés', 'Islandés'), ('Italiano', 'Italiano'), ('Japonés', 'Japonés'), ('Lituano', 'Lituano'), ('Noruego', 'Noruego'), ('Polaco', 'Polaco'), ('Portugués (BR)', 'Portugués (BR)'), ('Portugués (PT)', 'Portugués (PT)'), ('Rumano', 'Rumano'), ('Ruso', 'Ruso'), ('Serbio', 'Serbio'), ('Singalés', 'Singalés'), ('Sueco', 'Sueco'), ('Tailandés', 'Tailandés'), ('Turco', 'Turco'), ('Ucraniano', 'Ucraniano'), ('Urdu', 'Urdu'), ('Valenciano', 'Valenciano'), ('Vietnamita', 'Vietnamita'), ('Árabe', 'Árabe')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfilprofesional',
            name='lenguas_nativas',
            field=models.CharField(blank=True, choices=[('Alemán', 'Alemán'), ('Bosnio', 'Bosnio'), ('Búlgaro', 'Búlgaro'), ('Catalán', 'Catalán'), ('Checo', 'Checo'), ('Chino', 'Chino'), ('Coreano', 'Coreano'), ('Croata', 'Croata'), ('Danés', 'Danés'), ('Eslovaco', 'Eslovaco'), ('Esloveno', 'Esloveno'), ('Español', 'Español'), ('Español (MX)', 'Español (MX)'), ('Euskera', 'Euskera'), ('Filipino', 'Filipino'), ('Finés', 'Finés'), ('Francés', 'Francés'), ('Francés (CA)', 'Francés (CA)'), ('Gallego', 'Gallego'), ('Georgiano', 'Georgiano'), ('Griego', 'Griego'), ('Hebreo', 'Hebreo'), ('Hindi', 'Hindi'), ('Holandés', 'Holandés'), ('Húngaro', 'Húngaro'), ('Inglés', 'Inglés'), ('Islandés', 'Islandés'), ('Italiano', 'Italiano'), ('Japonés', 'Japonés'), ('Lituano', 'Lituano'), ('Noruego', 'Noruego'), ('Polaco', 'Polaco'), ('Portugués (BR)', 'Portugués (BR)'), ('Portugués (PT)', 'Portugués (PT)'), ('Rumano', 'Rumano'), ('Ruso', 'Ruso'), ('Serbio', 'Serbio'), ('Singalés', 'Singalés'), ('Sueco', 'Sueco'), ('Tailandés', 'Tailandés'), ('Turco', 'Turco'), ('Ucraniano', 'Ucraniano'), ('Urdu', 'Urdu'), ('Valenciano', 'Valenciano'), ('Vietnamita', 'Vietnamita'), ('Árabe', 'Árabe')], max_length=20, null=True),
        ),
    ]
