# Generated by Django 5.1.1 on 2024-09-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traductores', '0010_alter_combinacion_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinacion',
            name='servicios',
            field=models.CharField(choices=[('Traducción', 'Traducción'), ('Traducción jurada', 'Traducción jurada'), ('Revisión', 'Revisión'), ('Interpretación consecutiva', 'Interpretación consecutiva'), ('Interpretación simultánea', 'Interpretación simultánea'), ('Interpretación susurrada', 'Interpretación susurrada'), ('Interpretación telefónica', 'Interpretación telefónica'), ('Transcripción', 'Transcripción'), ('Locución', 'Locución'), ('Doblaje', 'Doblaje'), ('Maquetación', 'Maquetación')], max_length=100),
        ),
    ]
