# Generated by Django 5.1.1 on 2024-09-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traductores', '0011_alter_combinacion_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinacion',
            name='servicios',
            field=models.CharField(max_length=100),
        ),
    ]
