# Generated by Django 5.1.1 on 2024-09-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traductores', '0012_alter_combinacion_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinacion',
            name='debug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
