# Generated by Django 5.1.1 on 2024-09-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traductores', '0016_alter_perfilprofesional_textos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilprofesional',
            name='textos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
